// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp-W8Pu-f5B5L7PY4NqRKnviEDMu6OtnY',
    appId: '1:73252815940:web:d16cc90730dc612d39e811',
    messagingSenderId: '73252815940',
    projectId: 'spantry-1de44',
    authDomain: 'spantry-1de44.firebaseapp.com',
    storageBucket: 'spantry-1de44.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH_QRjjOzHS4Y0Fgi5Z8_K0kUSeF_FhoE',
    appId: '1:73252815940:android:1202a082cfc8a38e39e811',
    messagingSenderId: '73252815940',
    projectId: 'spantry-1de44',
    storageBucket: 'spantry-1de44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq0c4jyBHx6KiUitpYUJZ6b6eK5WWtRJ0',
    appId: '1:73252815940:ios:235f0f7fd55d07e439e811',
    messagingSenderId: '73252815940',
    projectId: 'spantry-1de44',
    storageBucket: 'spantry-1de44.appspot.com',
    iosBundleId: 'com.example.spantry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq0c4jyBHx6KiUitpYUJZ6b6eK5WWtRJ0',
    appId: '1:73252815940:ios:235f0f7fd55d07e439e811',
    messagingSenderId: '73252815940',
    projectId: 'spantry-1de44',
    storageBucket: 'spantry-1de44.appspot.com',
    iosBundleId: 'com.example.spantry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp-W8Pu-f5B5L7PY4NqRKnviEDMu6OtnY',
    appId: '1:73252815940:web:759b5c7ad919928039e811',
    messagingSenderId: '73252815940',
    projectId: 'spantry-1de44',
    authDomain: 'spantry-1de44.firebaseapp.com',
    storageBucket: 'spantry-1de44.appspot.com',
  );
}
